version: '2'
 
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_USER: sneezy
      MYSQL_PASSWORD: password
    container_name: sneezydb
    volumes:
      - sneezydb:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./db:/docker-entrypoint-initdb.d
      - .:/home/sneezy/sneezymud-docker  # for initially populating the DB
    expose:
      - "3306"
    restart: always

  sneezy:
    depends_on:
      - db
    build: ./docker
    container_name: sneezy
    cap_add:
      - SYS_PTRACE
    ports:
      - 7900:7900
    volumes:
      - .:/home/sneezy/sneezymud-docker
    restart: always

  web-frontend:
    build: ./web/frontend
    ports:
      - 3000:3000
    volumes:
      - './web/frontend:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development


    #  web:
    #    build:
    #      context: ./web
    #      dockerfile: web_Dockerfile
    #    ports:
    #        - "5001:5000"
    #    volumes:
    #        - ./web:/code
    #    depends_on:
    #        - db
    #    restart: always
volumes:
  sneezydb:
