version: '2'
 
services:
  db:
    #build: 
     # context: .
    #  dockerfile: ./db/Dockerfile
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_USER: sneezy
      MYSQL_PASSWORD: password
    container_name: sneezydb
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/etc/mysql
      - ./db:/docker-entrypoint-initdb.d
      - .:/home/sneezy/sneezymud-docker
    ports:
      - 3306:3306
    restart: always

  sneezy:
    depends_on:
      - db
    build: .
    container_name: sneezy-test
    ports:
      - 7902:7900
    volumes:
      - .:/home/sneezy/sneezymud-docker
      - ./mysql:/var/lib/mysql
    restart: always

  web:
    build:
      context: ./web
      dockerfile: web_Dockerfile
    ports:
        - "5001:5000"
    volumes:
        - ./web:/code
    depends_on:
        - db
    restart: always
